name: Regression Tests


on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Python ${{ matrix.python-version }} (${{ matrix.group }}/10)
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: myhdl/myhdl
        path: myhdl

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Icarus Verilog
      run: |
        sudo apt install -y --no-install-recommends iverilog

    - name: Setup myhdl
      run : |
        make -C myhdl/cosimulation/icarus
        cp myhdl/cosimulation/icarus/*.vpi .

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install myhdl

    - name: Test with pytest   
      run: |
        cd tb
        IVERILOG_VPI_MODULE_PATH=../myhdl/cosimulation/icarus/ pytest
